name: DomBot
description: 'DomBot is a simple AI Program designed for Bukkit Minecraft servers'
author: Dominic
main: com.domsplace.DomBot.DomBotPlugin
website: http://domsplace.com/
version: '1.00'
permissions:
    DomBot.dombot:
        description: Talk to the DomBot.